name: Snake Game

on:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snake-github-contributions

      - name: Run Snake Game
        run: python -m snake_github_contributions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
